# Generated by Django 2.2 on 2020-11-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('num', models.CharField(max_length=40)),
                ('p_date', models.CharField(max_length=23)),
                ('numOfCopies', models.IntegerField()),
            ],
        ),
    ]
